// Code generated by sqlc. DO NOT EDIT.

package DB

import (
	"context"
)

type Querier interface {
	Createfootballclub(ctx context.Context, arg CreatefootballclubParams) (Footballclub, error)
	Createplayer(ctx context.Context, arg CreateplayerParams) (Player, error)
	Createtransfer(ctx context.Context, arg CreatetransferParams) (Transfer, error)
	Createusers(ctx context.Context, arg CreateusersParams) (User, error)
	DeletePlayerByClubID(ctx context.Context, footballclubID int32) error
	Deletefootballclub(ctx context.Context, clubName string) error
	Deleteplayer(ctx context.Context, playerName string) error
	Deletetransfer(ctx context.Context, tID int32) error
	GetLasttransferByPlayerid(ctx context.Context, playerID int32) (Transfer, error)
	GetPlayersList(ctx context.Context, arg GetPlayersListParams) ([]Player, error)
	GetUsers(ctx context.Context, username string) (User, error)
	GetfootballclubByCountry(ctx context.Context, countryFc string) ([]Footballclub, error)
	GetfootballclubByID(ctx context.Context, fcID int32) (Footballclub, error)
	GetfootballclubByName(ctx context.Context, clubName string) (Footballclub, error)
	GetplayerByCountry(ctx context.Context, countryPl string) ([]Player, error)
	GetplayerByFootballclub(ctx context.Context, footballclubID int32) ([]Player, error)
	GetplayerByID(ctx context.Context, pID int32) (Player, error)
	GetplayerByName(ctx context.Context, playerName string) (Player, error)
	GetplayerByPosition(ctx context.Context, position string) ([]Player, error)
	GetplayerByValueHigherthan(ctx context.Context, value int64) ([]Player, error)
	GetplayerByValueLessthan(ctx context.Context, value int64) ([]Player, error)
	GettransferByPlayerid(ctx context.Context, playerID int32) ([]Transfer, error)
	GettransferByTransferid(ctx context.Context, tID int32) (Transfer, error)
	GettransferList(ctx context.Context, arg GettransferListParams) ([]Transfer, error)
	Highesttransfer(ctx context.Context) (Transfer, error)
	Latesttransfer(ctx context.Context, arg LatesttransferParams) (Transfer, error)
	Listfootballclub(ctx context.Context, arg ListfootballclubParams) ([]Footballclub, error)
	UpdatefootballclubBalance(ctx context.Context, arg UpdatefootballclubBalanceParams) error
	Updateplayer(ctx context.Context, arg UpdateplayerParams) error
	Updatetransfer(ctx context.Context, arg UpdatetransferParams) error
}

var _ Querier = (*Queries)(nil)
