name: ci-test

#triggers 
on:
  #event triggers
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

     # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: root
          POSTGRES_DB: simple_transfers
          POSTGRES_PASSWORD: krish@knight8
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Install Golang Migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.1/migrate.darwin-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/migrate
        which migrate

    - name: Run 1st Migrations
      run: make migrateup

    - name: Run 2nd Migrations  
      run: make migrateup1

    - name: Test
      run: make test
